fix(coverage) fix transpiling error
After git rebase, after adding html fixtures to unit testing ( v0.9.0 )
The following error appeared while running unit tests:

```
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  TypeError: 'Module' is not a function (evaluating '(0,_servicesGeolocationGeolocationJs2['default'])()')
  at http://localhost:9876/context.html:9
```

After some digging, the cause was an export/import of a default funtion.

It doesn't seem to be incorrect ES6, but at least, it's not best practice ...
So I made a named export out of this function - see the diff.